apiVersion: v1
kind: Namespace
metadata:
  name: website-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: minhajms/php-mysql-test:4.0
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "mysql-service.mysql-ns.svc.cluster.local"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: website-ns
spec:
  type: ClusterIP
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

